greasemonkey/greasemonkey

modules/parseScript.js
=> Regression: Localized name/descriptions don't work properly

modules/ipcscript.js
=> GM 3.0 - ignoring @noframes

content/scriptprefs.js
=> Unable to edit scripts in FF 38+

modules/xmlhttprequester.js
=> requests via GM_xmlhttpRequest in Private Browsing tends to steal the environment of the Public Browsing session

content/bindings.xml, content/config.js, content/scriptprefs.js, content/scriptprefs.xul, locale/cs/gm-cludes.dtd, locale/en-US/gm-cludes.dtd, modules/script.js, modules/stats.js, modules/sync.js
=> Display and edit @match rules in 'clude editor

components/greasemonkey.js, modules/ipcscript.js, modules/script.js
=> GM_info.version is "unknown", fix typo (description), add (noframes)

modules/xmlhttprequester.js
Add https://github.com/greasemonkey/greasemonkey/issues/2045, https://github.com/greasemonkey/greasemonkey/issues/2154, https://github.com/greasemonkey/greasemonkey/issues/2157.
Gist (test - https://github.com/greasemonkey/greasemonkey/issues/2045):
https://gist.github.com/janekptacijarabaci/bca6a7e0d1959cf542a0
Gist (test - https://github.com/greasemonkey/greasemonkey/issues/2154, https://github.com/greasemonkey/greasemonkey/issues/2157):
https://gist.github.com/janekptacijarabaci/08dab230b7b021e7b17a
=> GM_xmlhttpRequest - __exposedProps__: arraybuffer, blob, abort()

content/menucommander.js
Ad https://github.com/greasemonkey/greasemonkey/issues/2067
Is it a bug? Yes.
Is it a memory leak? Maybe yes.
=> GM_registerMenuCommand memory leak - maybe

modules/xmlhttprequester.js
Ad https://github.com/greasemonkey/greasemonkey/issues/2164
=> PrivateBrowsingUtils.isWindowPrivate/isContentWindowPrivate

modules/sandbox.js, modules/storageFront.js
Ad #2172
Gist: https://gist.github.com/janekptacijarabaci/97e7635cb7f496c005fa
=> GM_getValue: the returned objects are privileged JS objects

modules/installPolicy.js
=> [e10s on] Drag & Drop file (*.user.js) - the tab has crashed

content/menucommander.js
GM 3.2:
GM 3.3:
This patch: The suggestion (for example).
=> GM 3.3: GM_registerMenuCommand - no commands

modules/sandbox.js
=> Create sandboxes with sameZoneAs to reduce GC costs

modules/sandbox.js
fixes greasemonkey/greasemonkey#2070
=> use export helpers to avoid xray backscatter

content/browser.js, content/framescript.js, modules/processScript.js
build the dropdown menu asynchronously after requesting the frame URLs
through the message manager.
=> fixes greasemonkey/greasemonkey#2246

content/browser.js, modules/remoteScript.js
Ad https://github.com/greasemonkey/greasemonkey/issues/2202
Now - [e10s on]:
After fix this issue:
=> View source not working: fix for the context menu and [e10s on]

components/greasemonkey.js
Ad https://github.com/greasemonkey/greasemonkey/issues/2202#issuecomment-134398265
=> View source - fix for Firefox 38.0.5-

content/browser.js, modules/GM_openInTab.js
Ad #2141, #2153, #2247
Unfortunately, I can't think of anything better...
Gist: https://gist.github.com/janekptacijarabaci/014defb6c10c4d655e77
=> GM_openInTab: synchronize API with Tampermonkey (backward compatible)

content/browser.js, content/framescript.js, content/newscript.js
Ad #2151 (and the commit https://github.com/greasemonkey/greasemonkey/commit/6b05c4803c96ef4f947a229679e2160be13577af)
Current (nothing else I spotted):
Menu: "New User Script..."
The context menu: "View User Script Source"
=> Address "unsafe CPOW usage" warnings

content/browser.js
fixes duplicates introduced by 6b05c48
=> restore unique element filter on scripts dropdown menu

content/newscript.xul
Amendment to fix for commit https://github.com/greasemonkey/greasemonkey/commit/49b1cc813d324a32ff57744a3a954efd3ee29a04
See https://github.com/greasemonkey/greasemonkey/pull/2194#issuecomment-148831736
=> The "New User Script" dialog - "Includes" and "Excludes" - not wrapping lines

modules/requestObserver.js
=> Editing a @require line doesn't make the different version of the relevant file to be downloaded anymore

content/scriptprefs.js
Ad #2318
See also https://github.com/greasemonkey/greasemonkey/pull/2319
=> GM doesn't store user defined excludes

modules/addons4.js
Steps to reproduce:
- AOM: "Check for Updates" (or: "Find Updates"...)
- If the update makes - throws an warning in the Browser Console (FF 40+)
See also https://github.com/greasemonkey/greasemonkey/issues/2274#issuecomment-140872869
=> Minor fix - throws an warning in the Browser Console (update)

content/framescript.js
Ad #2371 
See also https://github.com/greasemonkey/greasemonkey/issues/1820
=> Script with @include about:blank?query (or #fragment) will be executed twice

modules/sandbox.js, modules/script.js, modules/util.js, modules/util/isPrivate.js, modules/util/windowIsPrivate.js, modules/xmlhttprequester.js
=> Feature Request: Support for detecting private mode.

content/browser.js, content/config.js, modules/remoteScript.js, modules/stats.js
Ad https://github.com/greasemonkey/greasemonkey/issues/2348#issuecomment-173367049
Tested on Linux and Windows (e10s: on/off).
=> The notification bar (persistence)

modules/remoteScript.js
=> The script name with suffix ".db"

modules/remoteScript.js
One example of a URL is:
https://github.com/anonim1133/wykop-userjs/blob/a86014414395f71e2b9f930cf8ec876374808c24/wykop-zawijas.user.js
See https://github.com/greasemonkey/greasemonkey/commit/fe737c78f61a83273eb2031a143c541b409d02eb#diff-fca536fb25de50f4f011771aa1a74483L593
See also https://forum.palemoon.org/viewtopic.php?f=56&t=12557 (Pale Moon 27+)
=> Infinite loading web page (*.user.js, e.g. MIME type: text/html) - Firefox <42

modules/sandbox.js
The suggestion.
Or missing import?
```
Components.utils.import("resource://gre/modules/NetUtil.jsm");
```
If it can be used in the future...
=> Minor fix - remove unused function

modules/storageBack.js
Ad https://github.com/greasemonkey/greasemonkey/commit/283259740e0405b81627d58ce4e5667f10509b69
=> Minor fix - unused __exposedProps__ (storageBack vs. storageFront)

modules/sandbox.js
Ad #2129
Gist: https://gist.github.com/janekptacijarabaci/91b78c87e694991e1599
=> GM_ functions don't work when called with `apply`

content/browser.js, content/browser.xul, locale/cs/gm-browser.properties, locale/en-US/gm-browser.properties, skin/browser.css
Ad #1868
__Thanks to jerone for contributing!__
@jerone
It's based on your code. I hope you don't mind :-)
=> Suggestion: Add a tooltip to the toolbar button

content/newscript.xul
=> The flexibility of the new script option

content/browser.js, modules/sandbox.js
1) Commands: Add localized script name (instead script name)
2) The tooltip (+ list of scripts): Add information about setting `@noscript`
=> Tooltip improvements

modules/util/getPreferredLocale.js
=> [FF 54+] Fix: Function GM_util.getPreferredLocale()

package.sh
This lets the extension be built on systems like OpenBSD and FreeBSD.
=> call bash from users env

src/content/edit-user-script.js
=> Made tabs a global constant

src/content/install-dialog.html, src/content/install-dialog.js
Deals with #2570 by migrating the install dialog to use Rivets.
=> Use rivets for install dialog

src/browser/monkey-menu.html
=> Add monkey-menu.run.js to loaded <scripts>

src/browser/monkey-menu.js, src/browser/monkey-menu.run.js
=> Clear pending uninstall ticker on unload menu

test/user-script-obj.test.js
For second part of #2670.
This will probably need some review for styling. Unfortunately there aren't too many tests in order to compare on some sort of style guideline.
=> Add unit test for calculateEval with EOF comment

src/browser/monkey-menu.js
=> Fix listing wrong active scripts due to many windows

src/parse-user-script.js
=> Prevent creating URL object with null base

src/content/edit-user-script.css, src/content/edit-user-script.html, src/content/edit-user-script.js
This adds a 'save' button next to the tabs. #2785
=> Add a save button

src/browser/monkey-menu.css, src/browser/monkey-menu.html, src/browser/monkey-menu.js, src/browser/monkey-menu.run.js, src/util/rivets-formatters.js
Partial implementation for #2639.
Basic keyboard navigation is supported. Up/down arrows.
=> Initial Accessibility Improvements for Monkey Menu

src/bg/user-script-registry.js
I find this is somewhat of a stop-gap to prevent further problems at the moment. But I'm hoping that my [current pull and later commits](https://github.com/greasemonkey/greasemonkey/pull/2719#issuecomment-348839520) can get merged at some point as they, somewhat by necessity in order to implement the async features, clean up the script install and update code paths.
=> Safely handle bad userscript save transactions

package.json, src/user-script-obj.js, test/user-script-obj.test.js
`randomInts[i].toString(16)` returns a string of length 1 or 2.
=> Make `_randomUuid()` always return string of length 36.

src/browser/monkey-menu.css
Refixes #2650 
Fixes the scrolling issue of #2816 
Seems to reduce (doesn't eliminate) the ghosting effect in #2816
Inadvertently fixes #2694
=> Monkey menu visual glitches

src/content/install-dialog.css, src/content/install-dialog.html, src/content/install-dialog.js
=> Fix install dialog issues

src/bg/user-script-registry.js, src/bg/value-store.js
Android does not support persist
https://github.com/greasemonkey/greasemonkey/issues/2827#issuecomment-362747577
=> Restore conditional persistence

src/browser/monkey-menu.html
Class tags that were missed in the MM re-styling.
=> Fix other user scripts heading style in MM

src/bg/user-script-detect.js
=> Catch parse errors in detect-script

_locales/en/messages.json, src/bg/user-script-registry.js
=> Localize 'Script Save Error'

_locales/de/messages.json
Solves #2853 (for german messages)
=> Update german strings from transifex with placeholders

src/bg/on-user-script-notification.js
=> Only use notification port if it exists.

src/content/edit-user-script.html, src/content/edit-user-script.js
This is PR #2850 continued! The last commit was missing during merge...
=> Smarter solution for translation of attributes with rivets

src/browser/monkey-menu.css
This helps with #2868.
I don't want to say 'fixes' because the text is still off. See https://github.com/greasemonkey/greasemonkey/issues/2868#issuecomment-368278261
=> Remove -moz-box and float from Monkey Menu

_locales/en/messages.json, src/content/install-dialog.js
Helps with #2869
Also fixes #2866
=> Wait for install before closing dialog

src/downloader.js
=> Fix ReferenceError with iconDownload

_locales/en/messages.json, src/content/install-dialog.js, src/downloader.js
Continued effort to improve error handling in the downloader.
refs #2869 
---
The editor will also need improvements but that's for another PR.
=> Differentiate Download Errors

src/downloader.js
We should really move on switching to browser.
=> Remove async from promise constructor in downloader

src/browser/monkey-menu.run.js
=> Stop using (deprecated) keypress event

src/content/edit-user-script.js
=> Prompt for confirmation before leaving unsaved editor

src/content/cm-addons/lint-metadata.js, test/content/cm-addons/lint-metadata.test.js
Lint handling issues in meta data block...
Fixes #2918
Fixes #2917
=> Lint magic numbers / error in lint message

_locales/de/messages.json, _locales/en/messages.json, src/browser/monkey-menu.html
Localizes newly added userscript details in `Greasemonkey` menu
=> Localize menu userscript details

src/browser/monkey-menu.css
Prevents nested scrollbars.
fixes #2809 
Might be decent to look into a more "dynamic" way to do this. Maybe grid layout or something?
=> Reduce size of script section in MM

src/bg/value-store.js
Same code styling changes that happened to the registry some time ago. Now applied to the value-store.
=> Use async functions and await to reduce nesting in value-store

src/parse-user-script.js
=> Prepare defaults when returning details from script parser

src/bg/export-db.js
=> Fix obscure case of name conflicts on exporting a backup

src/browser/monkey-menu.html, src/browser/monkey-menu.js, src/content/edit-user-script.html, src/content/edit-user-script.js, src/content/install-dialog.html, src/content/install-dialog.js, src/parse-user-script.js, src/user-script-obj.js, src/util/get-best-locale-match.js, src/util/i18n-user-script.js, src/util/rivets-formatters.js, test/parse-user-script.test.js, test/utils/get-best-locale-match.test.js, test/utils/i18n-user-script.test.js
Resolves https://github.com/greasemonkey/greasemonkey/issues/3089
=> Revive i18n of @name and @description

src/browser/monkey-menu.css
Resolves https://github.com/greasemonkey/greasemonkey/pull/2770#issuecomment-764838005
=> Make the menu be not cut off when “User script commands” is added
