greasemonkey/greasemonkey

modules/sync.js

Since GM_ScriptStorageBack.getValue now returns a JSONified value which is parsed on the frontend, this needs a `JSON.parse`.  Currently (version 3.1beta1) it's breaking script values (`5` to `"5"`, `'foo'` to `'"foo"'`) if `extensions.greasemonkey.sync.values` is turned on.

Fix syncing of script storage.

---

skin/bindings.css

Add https://github.com/greasemonkey/greasemonkey/commit/4d5039598c8f929da89477334ebcae5cc1444a80
Repair pull request (@matchInCludeEditorEditing #2126) for #1703.
__My mistake, I'm sorry.__

Display and edit @match rules in 'clude editor - fix

---

content/scratchpad-overlay.js
install.rdf
modules/xmlhttprequester.js

Add #2038.
I've been personally running this on PM 25.2.1x64 for a couple weeks now without problem, though I haven't tested extensively beyond my normal usage.

Pale Moon Support

---

content/config.js

The 'use strict' - after installing a script (and not exists) - throws the warning

---

content/browser.js

``` javascript
// browser.tabs.loadInBackground = true
GM_openInTab(url, false); // open the page in the background
```

GM 3.2+: GM_openInTab(url, false) - open the page in the background

---

modules/remoteScript.js
modules/scriptProtocol.js
modules/util/getBinaryContents.js
modules/util/getContents.js

Ad #2202
__It is necessary to test all options (e.g.: correct permissions / the correct principal?)!__
nsIOService::NewChannelFromURI is deprecated:
https://hg.mozilla.org/mozilla-central/file/66a72727e1b3/netwerk/base/nsIOService.cpp#l603
Unfortunately, there are no references to the "NewChannelFromURI2" APIs in the documentation...
The short documentation:
https://hg.mozilla.org/mozilla-central/file/66a72727e1b3/netwerk/base/nsIIOService.idl#l68

[e10s]: newChannelFromURI - it sometimes throws the error

---

modules/util/setEditor.js

Fixes: https://github.com/greasemonkey/greasemonkey/issues/2271

Allow .cmd as editor executable. Fixes #2271 

---

content/browser.js
content/menucommander.js

Ad: https://github.com/greasemonkey/greasemonkey/commit/baa276244730bbb506feb68a8223c57e32d41099
Fix synchronization of commands between popups (and after a page refresh F5 - if the number of commands change: 0, >0).
1st step:
2st step:
Ad / See: https://github.com/greasemonkey/greasemonkey/issues/2276

GM 3.3beta2+, GM 3.4beta2+: Fix synchronization between popups

---

content/addons4-overlay.js

Ad https://github.com/greasemonkey/greasemonkey/issues/2274#issuecomment-140902678
__I think it has to do with it being version 3.4.1, but I sometimes write too complicated (or too simple) :-) Maybe both at once :-)__
1) I trying make a new profile of Firefox
2) Installing Greasemonkey (v3.4.1)
3) Installation of this script (e.g.):
``` javascript
// @name        test
// @include     *
// @version     1.0
// @grant       none
// @downloadURL http://localhost/test.user.js
alert("hi");
```
4) I change a script (file) on the "server" (@version 1.0 => @version 1.1), saving
5) Firefox => Add-ons Manager => Right-click on the script and click "Find Updates"
6a) GM 3.4.1 - the result:
6b) GM 3.4beta3- - the result:

GM 3.4.1: If just one script is installed (and updated)

---

modules/xmlhttprequester.js

Ad #2221
Gist: https://gist.github.com/janekptacijarabaci/a177abe49c9a26bb77e1
P.S.
```
Components.utils.importGlobalProperties(["Blob"]);
```
works in firefox 35+ (the minVersion in install.rdf).

GM_xmlhttpRequest binary mode not working

---

content/config.js

Ad https://github.com/greasemonkey/greasemonkey/blob/3.5/content/config.js#L247
See also #2318

Show notifications about parse errors

---

content/install.js
modules/remoteScript.js

Steps to reproduce:
- I have a script with @resource (i.e. https://gist.github.com/arantius/1157543#file-api-tester-user-js)
- During installation, press “Show Script Source”
- Close view tab
- Throws an error in the Browser Console
See https://github.com/greasemonkey/greasemonkey/blob/3.5/modules/remoteScript.js#L469:
https://github.com/greasemonkey/greasemonkey/blob/3.5/modules/remoteScript.js#L267
(aErrorMessage = [object UIEvent])

Minor fix - throws an error in the Browser Console

---

content/browser.xul

Ad https://groups.google.com/forum/#!topic/greasemonkey-users/ZoBo7wJEIZI
The context menu of Firefox ≠ The context menu of Greasemonkey (icon)

The context menu - jumps up a bit

---

modules/scriptProtocol.js

Ad #2341
The error in the Browser Console:
Ad https://github.com/greasemonkey/greasemonkey/commit/9dac77c4fc9cb89b31701e41c321f6712055a81c

Cannot use an image file that is locally downloaded via @resource, as an icon in a `input` element

---

components/greasemonkey.js

User-specified include/exclude rules require Firefox restart to take effect

---

modules/remoteScript.js

The user script:
``` javascript
var something;
```
Throws an error in the Browser Console:
The reason is:
1) https://github.com/greasemonkey/greasemonkey/commit/21196c5bc1a34f23df0c1805d1e9c088359a5777
2) The same unfixed bug: https://github.com/greasemonkey/greasemonkey/commit/f5b2de99840791d4d3f0844617a9c2d00d01ca04

GM 3.7beta3: Throws an error in the Browser Console (if metadata not found)

---

content/browser.xul

Upon getting into Firefox the first time: I click to bring up the main menu the menu jumps up a bit.
If it is true that: "No installed scripts run on this page."...
See also https://github.com/greasemonkey/greasemonkey/pull/2337

Minor fix - the main menu - jumps up a bit

---

components/greasemonkey.js
content/options.js

Changes to global excludes should be active after tab reload.
See also #2361
(the problem is not completely solved)

Global exclude rules require Firefox restart to take effect

---

content/browser.js
content/menucommander.js
modules/prefmanager.js

Currently GM leaks top level windows when you Ctrl+N, Ctrl+W (i.e. simply open and close).
This cleans up the dangling references.

fix leaks when opening&closing chrome windows

---

components/greasemonkey.js
modules/ipcscript.js
modules/scriptProtocol.js

- eliminates different code paths for parent/child
- eliminates a sync messages
- fewer Lines of Code
Tested against test script provided by @daniels1989 in #2326

Always use IPC scripts for greasemonkey-script: scheme

---

modules/miscapis.js
modules/sandbox.js
modules/util/fileXhr.js

Ad https://groups.google.com/forum/#!topic/greasemonkey-users/b1UexmfFN1A 
Gist: https://gist.github.com/janekptacijarabaci/e2b932e73216fbe00fb2
But maybe it's better to solve this problem: https://github.com/greasemonkey/greasemonkey/issues/2042

Suggestion: GM_getResourceText - binary (backward compatible)

---

modules/xmlhttprequester.js

For example:
``` javascript
// @name        GM_xmlhttpRequest() - if an error occurred, error object throws error
// @include     *
// @grant       GM_xmlhttpRequest
try {
GM_xmlhttpRequest();
} catch (e) {
alert(e);
}
```
Firefox throws an errors in the Error Console:
`Permission denied to access property Symbol.toPrimitive`
Last bad: 2016-07-13
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/04821a70c739a00d12e12df651c0989441e22728
First good: 2016-07-14
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/08f8a5aacd8308a73f6040fe522be7ba38497561
Pushlog …

GM_xmlhttpRequest() - if an error occurred, error object throws error

---

CONTRIBUTING.md

Points user to forum and Stack Overflow for questions, in order to avoid questions like #2449 and #2452.

Update CONTRIBUTING for issue rule

---

components/greasemonkey.js
modules/miscapis.js
modules/sandbox.js
modules/util.js
modules/util/loadFile.js

Fixes #2485
Turns out the basic `@resource` handling stuff was easy enough, with a caveat:
It's not possible to structured-clone some `responseType`s. Of course, this didn't work before already, but when trying to structured-clone some types via IPC, the child process will actually crash o_O. This was the case too for `blob`, thus I opted to load that to as `ArrayBuffer` and reconstruct the `Blob` again child-side.
Tested in e10s windows, but also in non-e10s windows to make sure stuff didn't break.
I *think* I didn't use features above the `minVersion`...

Fix e10s sandbox preventing scripts to load

---

src/content/install-dialog.css

On the install script dialog page the buttons are not the exact same size. This is due to some weird flex-box parsing and the contents of the elements that have 'flex-grow' set. Turns out setting [width: 0](https://stackoverflow.com/a/7985973) on the elements fixes the issue and they become the same size.

Normalize install button sizes

---

content/config.js

[See my comment in the issue.](https://github.com/greasemonkey/greasemonkey/issues/2600#issuecomment-333315111)
An additional note. While this fixes the initial issue, there's still the problem of scripts that have already been migrated and are suffering from the problem. Since already migrated scripts are [skipped](https://github.com/greasemonkey/greasemonkey/blob/3.x/content/config.js#L414-L418).

Parse migration values. Fixes #2600

---

manifest.json
src/bg/api-provider-source.js
src/bg/on-user-script-notification.js
src/bg/on-user-script-open-in-tab.js

GM.openInTab(url, openInBackground = true)
GM.setClipboard(text)
GM.notification(details, ondone) / GM.notification(text, title, image, onclick)
**Test script:**
https://gist.githubusercontent.com/xor10/973c4fb17671dac987676e1b11d136ab/raw/39521431d17d61a7d8a161e2f4dec5668d9f7991/test_api.user.js
```javascript
// @name        Test
// @version     1.0.0
// @namespace   @XOR
// @include     *example.com*
// @grant       GM.notification
// @grant       GM.openInTab
// @grant       GM.setClipboard
GM.openInTab('https://www.google.com');
GM.setClipboard('Hello World');
GM.notification({text: 'This is a text', title: 'Notification 2', onclick: () => console.log('NotificationClick') });
```

Add GM.notification, GM.openInTab and GM.setClipboard

---

src/user-script-obj.js

#2627, #2628
Added missing keys per Greasemoneky documentation wiki:
https://wiki.greasespot.net/GM_info
Three keys were not implemented.
isPrivate; a function fo the current tab, and therefore cannot be
cached.
scriptWillUpdate; There doesn't seem to be a property that defines
if a script is slated for autoupdate.
unwrap; ??
---
Of note, the uuid key was moved under the script key. It didn't make much sense that the _script_ uuid was not part of 'script'.
Of further note, this will solve the problems for new scripts but since the data is cached the `GM.Info` object will not be updated until the scripts are resaved. Even more nuanced, the resource objects won't be updated to include the url until they are each modified and saved.

Add missing info to GM.Info per docs

---

src/browser/monkey-menu.js

For #2638.
When constructing the submenu for an individual script the [original script objects](https://github.com/greasemonkey/greasemonkey/blob/eacbd15801dca70d3be0e444689dba333dc5f0c7/src/browser/monkey-menu.js#L74-L78) are used. These were not updated when toggling enable / disable.

Update userscript object enabled on toggle

---

src/parse-user-script.js

If a script which had the noframes metablock item and then it were
to remove it the old value (noframes=true) would remain. This
fixes that issue by configuring a default value for noframes.

Fix not saving noframes by setting default

---

src/user-script-obj.js

See #2651.
Doesn't solve the issue but does allow for graceful failure.

Gracefully fail _testMatch if bad type is passed

---

src/user-script-obj.js

See #2670 
When a user script had a trailing comment it would comment out part
of the eval string. Catch them so they don't interfere.

Fix failing with trailing comments in scripts

---

src/browser/monkey-menu.css
src/content/edit-user-script.css

Small UI fix. You can't select text with the cursor in the money menu or the tab on the editor page anymore.

Don't allow selectable text in the monkey menu and tabs in script editor

---

src/content/edit-user-script.js

CodeMirror's default keymap already handles 'ctrl-s' and even runs
a 'save' command when available.
see docs
https://codemirror.net/doc/manual.html#commands

Issue #2690 Define a codemirror "save" command

---

src/bg/on-user-script-xhr.js

This should fix #2712, the problem is due to referencing an incorrect variable `evt` instead of declared `event`.

Fix GM.xhr onprogress event is not working

---

src/browser/monkey-menu.html

At the moment there is no visible separation between the Greasemonkey function add new script and the urls for further information. This pull request adds a new line to have a visible separation between both.

Add additional line between GM functions and urls, solves #2697

---

karma.conf.js
test/bg/user-script-registry.test.js
test/third-party/MatchPattern.test.js
third-party/MatchPattern.js

Super simple fix prescribed by @arantius, fixes #2715.
Tested with this branch loaded as a temporary webext in FF 57 and it does indeed fix the issue (obviously).

Include query string in MatchPattern URL test

---

src/user-script-obj.js

The initial change fixed the problem but only as a side effect that
typeof returned 'object' for everything. Therefore any object would
fail the comparison and get caught.

Fix logical flaw from 7d1f1b98

---

src/content/edit-user-script.css

The editor has a layout issue that is affecting typing speed. Removing `display: flex` from the `.CodeMirror` selector should fix this.

Remove CodeMirror flexbox style

---

src/bg/is-enabled.js

Trying to toggle greasemonkey on or off fails right now on Android due to a missing API. Check for setIcon before we call it.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setIcon#Browser_compatibility

Avoid crash in setIcon on Firefox for Android

---

src/browser/monkey-menu.js

Document#getElementsByTagName() returns live collection but ParentNode#querySelectorAll() returns static collection.

Repair keyboard navigation on user script list in monkey menu.

---

src/user-script-obj.js

The #2771 fix has a bug in it. If you don't supply the optional async parameter it defaults to undefined, which evalulates to false. It should default to true if it's not supplied. This fixes the xhr shim.

fix XMLHttpRequests that don't have the "async" parameter

---

src/bg/user-script-registry.js

Ran into this developing my last patch. Allowing for version downgrades on evalContent should be allowed.

Support downgrading evalContentVersion on scripts

---

src/user-script-obj.js
test/user-script-obj.test.js

Allow scripts to execute on the `file:` protocol

---

test/third-party/MatchPattern.test.js
third-party/MatchPattern.js

I don't recall how I stumbled upon this, but I found out that `MatchPattern.js` doesn't quite follow Google's specification. `file:///foo*` is a valid match pattern but the previous code would not allow it. A fix to the Regex solved that problem.
Also added a bunch of tests.

Fix matchpattern `file:` match

---

src/bg/on-user-script-open-in-tab.js

Some addons (for example, [Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/)) refers `openerTabId` of tabs to detect their relation. The parameter is supported by both Google Chrome and Firefox (57+).

Specify openerTabId for tabs from GM.openInTab.

---

manifest.json
skin/icon.svg
src/bg/is-enabled.js

Close #2739 
Hope you like it.
Toolbar:
Disabled:
<details><summary>Old Screenshots</summary>
Toolbar:
Inactive:
</details>

Use SVG icons

---

src/browser/monkey-menu.css
src/browser/monkey-menu.html
src/browser/monkey-menu.js

Overhaul the styling to much more closely mimic FF 57 + menu / panel design. Also includes a similar transition effect as seen in native FF menus.

Adjust Monkey Menu to look and behave like native FF

---

src/bg/on-user-script-open-in-tab.js

Fixes https://github.com/greasemonkey/greasemonkey/issues/2672 .
This uses `openerTabId` property of `tabs.create()` that implemented in Firefox 57.
https://developer.mozilla.org/Add-ons/WebExtensions/API/tabs/create
```javascript
// @name     GM.openInTab() Test
// @version  1
// @match    https://github.com/greasemonkey/greasemonkey/issues/2672
// @grant    GM.openInTab
const parent = document.getElementsByClassName('gh-header-show')[0];
parent.insertAdjacentHTML('beforeend', `
<button name="open-in-background-tab">Open the wiki in background tab</button>
<button name="open-in-active-tab">Open the wiki in active tab</button>
`);
parent.addEventListener('click', function (event) {
switch (event.target.name) {
case 'open-in-background-tab': …
```

Make `GM.openInTab` open a tab in a correct place in Firefox 57+.

---

src/bg/value-store.js
test/bg/value-store.test.js

Unlink value-store functions from the messaging interface so that
they can be called directly from the background script, should the
need arise.
Useful for tests and for #2747

Separate value-store implementation from messaging

---

src/bg/user-script-registry.js
src/bg/value-store.js
test/setup.js

See #2675 for discussions.
Persistent DBs will only be used for FF >= 57. The reason is that the persistent APIs are not supported on older versions. The only way to persist is to use the non-standard `{storage: 'persist'}` option. Unfortunately that option makes migration from 'non-persisted' to 'persisted' very difficult.
See [this comment](https://github.com/greasemonkey/greasemonkey/issues/2675#issuecomment-349675249) for more background information.

Add persistence to GM databases

---

manifest.json
src/bg/on-user-script-xhr.js

Even in WebExtensions, Firefox enforces [per spec](https://fetch.spec.whatwg.org/#forbidden-header-name) that Referer, Origin, and other headers may not be set by the developer on the XHR object. However, if the outgoing XHR is intercepted in the `onBeforeSendHeaders` event, it is possible to set these headers as desired.
~~This is a WIP~~ This change currently looks for Referer and Origin and shows how GM can set the header values when the user supplies them the normal way, through the `headers` property of the object passed to `GM.xmlHttpRequest`. It's necessary for GM to add dummy headers to preserve the user's header values until `onBeforeSendHeaders`, at which point we can set the real header and delete the dummy.
Fixes https://github.com/greasemonkey/greasemonkey/issues/2599

Allow user to set forbidden headers in XHR

---

src/bg/user-script-registry.js
test/bg/user-script-registry.test.js

- `indexedDB.deleteDatabase('greasemonkey')` will be blocked until tests completed because user-script-registry.js leave the database openning.
- Now the second `assert.isOk(scriptNamed('footnote'));` in user-script-registry.test.js will be executed before executing `UserScriptRegistry._loadUserScripts();` is completed.

Make `UserScriptRegistry._loadUserScripts()` return Promise for tests.

---

_locales/de/messages.json
_locales/en/messages.json
src/browser/monkey-menu.html

In accordance with Firefox menus and Greasemonkey 3.x menu.
See https://github.com/greasemonkey/greasemonkey/pull/2770#discussion_r165088332 .

Remove superfluous SPACEs before "..." in the Monkey Menu.

---

src/bg/api-provider-source.js

Several GM.* API functions are using _(...) for localized error messages.
A reference to the function in `src/i18n.js` is missing.
So a private copy of that code had to be imported to the API header.

Add missing _() function to API scope

---

_locales/de/messages.json
_locales/en/messages.json
src/browser/monkey-menu.js

A new unnamed script uses `// @name Unnamed script`, followed by a number.
This change makes it possible to use a localized name instead ($1 is the random number).

Use a localized name for a new unnamed script (with placeholder $1)

---

src/content/edit-user-script.html

Handles #2874 
Missing reference to MatchPattern:
```
Error: Ignoriere @match-Eintrag * aus folgendem Grund:
Error: @match: Could not parse the pattern.  parse-user-script.js:114:15
```

Include MatchPattern properly in the editor

---

src/downloader.js

It is never used and the automatic promise returned
from `async start()` can be used as a sufficient
replacement.

Remove completion promise from UserScriptDownloader

---

src/bg/user-script-registry.js
test/bg/user-script-registry.test.js

Flattens the code. Removes unnecessary async. Uses `.catch` rather than `try .. catch` (huh?). Removed all the duplicate `db.close()`, you only have to close the db after you finish specify the commands you want to execute. The db won't close until those commands complete.
Also, what's the point of "RemoteUserScript". It's effectively useless. Created ***JUST*** for the `id`? Seems silly to me to have a class that doesn't do anything.

Cleanup async functions in user script registry

---

manifest.json
src/bg/on-user-script-xhr.js

Normally, a background script XHR will only include cookies if third-party cookies are enabled in Firefox. These changes fix that using the `cookies` WebExtension API, giving `GM.xmlHttpRequest` cookie behavior identical to that of a normal XHR. Same-origin requests have cookies included automatically, and cookies can be included for cross-origin requests with the opt-in `withCredentials` parameter.
These changes only take effect if the user has not specifically passed a `Cookier` header to `GM.xmlHttpRequest`. If they do so, those values are sent and no further action is taken. This has the added benefit of allowing the user to opt out of automatic cookies on same-origin requests by manually passing an empty `Cookie` header.
If we don't want the cross-origin/withCredentials stuff, that …

Include cookies in GM.xhr for same-origin; implement withCredentials for cross-origin

---

src/browser/monkey-menu.css
src/browser/monkey-menu.html
src/util/rivets-formatters.js

Scroll only userscript section in Monkey Menu

---

_locales/en/messages.json
doc/Messages.md
src/bg/user-script-registry.js
src/content/edit-user-script.css
src/content/edit-user-script.html
src/content/edit-user-script.js
src/downloader.js
test/bg/user-script-registry.test.js

Use save modal with editor

---

src/content/edit-user-script.js

This change retrieves script details from the background and passes the `enabled` setting to the downloader. If the background sends back undefined, fallback to gUserScript.

Don't re-enable scripts when saving in editor

---

src/content/edit-user-script.html
src/content/edit-user-script.js

It was already present in the codebase, just not being used. This enables quick
line toggling by pressing `Ctrl-/` or `Cmd-/` on mac.

Use CM comments add-on

---

src/bg/on-user-script-xhr.js

Always set status, statusText, and responseHeaders

---

_locales/en/messages.json
src/bg/options.js
src/browser/monkey-menu.html
src/browser/monkey-menu.js
src/content/edit-user-script.js

This is needed by screen reader users, as CodeMirror is unfortunately not accessible. Having a separate editor is not ideal, nor is the missing functionality for screen reader users. Nevertheless, this is far better than a completely inaccessible editor. This at least allows screen reader users to read the content and do basic editing.
A more ideal alternative would be switching to [Monaco](https://microsoft.github.io/monaco-editor/), which is accessible. This would avoid the need for a separate editor and provide advanced functionality for all users. I'm not sure if that is feasible, though.

Add an optional simple editor which uses a plain textarea.

---

src/browser/monkey-menu.css
src/browser/monkey-menu.html
src/browser/monkey-menu.js

Previously, screen readers reported nothing when the user switched to a new section. With this change, each section is exposed as a dialog, with the active dialog getting focus. This way, a screen reader will report the content of the new section as if a dialog appeared.
I separated this from #3058 because this one is a bit more controversial, since it messes with focus a tiny bit. Also, I'm totally blind, so I can't confirm whether focusing the sections causes problems visually.

Expose sections as dialogs for accessibility.

---

_locales/en/messages.json
src/browser/monkey-menu.html
src/browser/monkey-menu.js
src/content/edit-user-script.html

This makes Greasemonkey far more usable by screen reader users.
Even though keyboard navigation is implemented for the Monkey Menu, this change exposes it as buttons, rather than menu + menuitems. This is because unlike most menus, this menu contains headings, which doesn't fit the ARIA menu pattern. This way, screen reader users will be able to browse this like any other document and will be made aware of (and able to jump to) the headings.

Add accessibility semantics and labels.

---

test/scripts/script-server-slow.py
test/scripts/script-server-update.py

I do not use Python 2 because it is end-of-life, so I fixed the scripts in `test/scripts` with a name ending with `.py` to make them work with currently supported Python versions, instead of making it only work with Python 2.
Differences:
* The `print` statement no longer exists in Python 3, but a function with the same name provides the same behaviour.
* `BaseHTTPServer` was renamed to `http.server` in Python 3.
After this, when the next version is released, open a security advisory in the `Security` tab to have others upgrade to the latest version as Python 2 will not get anymore updates, even critical security fixes.
**I mean, Python 2 is actually EOL! It was EOL 2 years right after the scripts were added. See https://python.org/doc/sunset-python-2 and …

Fix python scripts to work with Python 3

---

src/bg/updater.js

GreaseMonkey computes the next scheduled update for each script each time it successfully automatically checks for an update. This information is used to select the next script which automatically check for an update. This change ensures that scripts which do not have this information stored (i.e., scripts which have yet to have a successful automatic update check) will perform their initial automatic update check regardless of the order in which scripts are iterated.
Due to the existing parameters and tuning in GreaseMonkey, this change will result in any update-eligible scripts which have not had their updates checked causing a 3-hour pause of updates. You must ensure that you keep your browser open for at least 3 hours for each script which has not had an automatic update check …

Fix issue preventing some scripts from auto-updating.
